receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

exporters:
  logging:
    verbosity: detailed

  # prometheus:
  #   endpoint: prometheus:8888

  # otlp:
  #   endpoint: jaeger:4317
  #   tls:
  #     insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, zipkin]
